apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}
spec:
  template:
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: physim
        image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
#        resources:
#          requests:
#            memory: "4096Mi"
#            cpu: "4000m"
#          limits:
#            memory: "4096Mi"
#            cpu: "4000m"
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        env:
        - name: OPENAIR_DIR
          value: /opt/oai-physim
        command: ["/bin/sh", "-c"]
        args:
        - >
          cmake_targets/autotests/run_exec_autotests.bash -g "dlsim.basic" -d bin/ &&
          echo "FINISHED"
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      serviceAccountName: oai-physim-sa 
      terminationGracePeriodSeconds: 30
