kubernetesDistribution: Vanilla #Vanilla for community kubernetes distribution else Openshift for Openshift

# Add this section to allow the pod to use the ip address of the cluster node
hostNetwork: true

nodeSelector:
  kubernetes.io/hostname: oran-25-36 # Replace with your actual node name

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - oran-25-36 # Replace with your actual node name

## In case of using these charts on Openshift then please use UBI images
## To know more about them follow this tutorial https://gitlab.eurecom.fr/oai/cn5g/oai-cn5g-fed/-/tree/master/openshift
nfimage: # image name either locally present or in a public/private repository
  repository: localhost/ran-build
  version: latest # image tag or develop
  # pullPolicy: IfNotPresent or Never or Always
  pullPolicy: Never

# good to use when pulling images from docker-hub mention 
imagePullSecrets:
- name: "regcred"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "oai-gnb-sa"

# service:
#   n3NodePort: 32152 # Add this line. Choose a port between 30000-32767
#   n2NodePort: 32412 # Add this line. Choose a port between 30000-32767

#service type is fixed to clusterIP, it is only support for non multus interface (eth0)

# These helm-charts can be used for two purpose
# 1. RFSimulated oai-gNB: Only requires 1 interface for N2 and N3. You can use Kubernetes default interface eth0
# 2. Physical gNB with Ethernet based USRP or RRU: You need to use ruInterface to connect with RU. Make sure that the ip-address you choose can reach to RU. 
#                                                 Using a dedicated interface for N2 or N3 is optional you can still use eth0. 
# 3. Another thing you can chose to use same virtual interface for N2/N3 its optional to have two different

## NOTE: To use these charts with USRP B210 you need to modify and mount usb from the host. 
## Change these ip-addresses according to your environment


multus:
  # if default gatway is empty then it will be removed
  defaultGateway: ""
  n2Interface:
    create: false
    name: "n2"
    ipAdd: "10.5.25.36"
    netmask: "22"
    # if gatway is empty then it will be removed
    #gateway: "172.21.7.254"
    #routes: [{'dst': '10.8.0.0/24','gw': '172.21.7.254'}, {'dst': '10.9.0.0/24','gw': '172.21.7.254'}]
    hostInterface: "eno1" # Interface of the host machine on which this pod will be scheduled
  n3Interface:
    create: false
    ipAdd: "10.5.25.36"
    name: "n3"
    netmask: "22"
    # if gatway is empty then it will be removed
    #gateway: "172.21.11.254"
    #routes:
    hostInterface: "eno1" # Interface of the host machine on which this pod will be scheduled
  ruInterface: #Only needed if using a ethernet based RU/USRP
    create: false
    ipAdd: "192.168.80.90"
    name: "ru"
    netmask: "24"
    # if gatway is commented then it will be removed
    gateway: "192.168.80.1" #In case you don't have a gateway remove it from here
    ## The value must be [0, master's MTU]. If commented it will masters MTU
    #mtu: 1500
    hostInterface: "bond0" # Interface of the host machine on which this pod will be scheduled

## If you want to change more configuration parameters then you should mount the config file  
# in templates/configmap.yaml
# Example config files --> https://gitlab.eurecom.fr/oai/openairinterface5g/-/tree/develop/targets/PROJECTS/GENERIC-NR-5GC/CONF 
config:
  #timeZone: "Europe/Paris"
  timeZone: "Europe/London"
  useAdditionalOptions: "--sa --rfsim --gNBs.[0].min_rxtxtime 6 --log_config.global_log_options level,nocolor,time"
  gnbName: "gNB-OAI" # oai-gnb-rfsim
  mcc: "235" # check the information with AMF, SMF, UPF
  mnc: "92" # check the information with AMF, SMF, UPF
  tac: "4200" # check the information with AMF
  sst: "1" #currently only 4 standard values are allowed 1,2,3,4
  usrp: rfsim #allowed values rfsim, b2xx, n3xx or x3xx
  amfhost: "10.5.25.208" # amf ip-address or service-name oai-amf-svc or 172.21.6.94
  n2IfName: "eno1" # if multus.n2Interface.create is true then use n2
  n3IfName: "eno1" #if multus.n3Interface.create is true then use n3 or you can only use 1 interface n2 or eth0 
  ricAddress: "10.5.25.33"
  ricPort: "36421"

## Debugging section
start:
  gnb: true #If false the network function container will run in sleep mode for manually testing
  tcpdump: false

includeTcpDumpContainer: false #If true it will add a tcpdump container inside network function pod for debugging

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

securityContext:
  privileged: true # Changed to true, it was by default false
  capabilities:
  add: ["NET_ADMIN", "SYS_NICE"]

tcpdumpimage:
  repository: docker.io/oaisoftwarealliance/oai-tcpdump-init
  version: alpine-3.20
  #pullPolicy: IfNotPresent or Never or Always
  pullPolicy: IfNotPresent

## NF is the network function and tcpdump is the tcpdump container. 
## To know more about request and limit it is better to understand that how Kubernetes QoS works. 
## https://kubernetes.io/docs/concepts/configuration/manage-resources-containers
## https://kubernetes.io/docs/concepts/workloads/pods/pod-qos
resources:
  define: false
  limits:
    nf:
      cpu: 2000m
      memory: 2Gi
    #If tcpdump container is disabled this value will not be used
    tcpdump:
      cpu: 200m
      memory: 128Mi
  requests:
    nf:
      cpu: 2000m
      memory: 2Gi
    #If tcpdump container is disabled this value will not be used
    tcpdump:
      cpu: 100m
      memory: 128Mi

tolerations:
- key: "node-role.kubernetes.io/control-plane"
  operator: "Exists"
  effect: "NoSchedule"

affinity: {}

terminationGracePeriodSeconds: 5

nodeSelector: 
  kubernetes.io/hostname: oran-25-36

nodeName:
