version: '3.8'

services:
    enb_mono_fdd:
        image: oai-enb:latest
        privileged: true
        container_name: lte-b200-enb-fdd-10Mhz-tm1
        environment:
            USE_FDD_MONO: 'yes'
            USE_B2XX: 'yes'
            ENB_NAME: eNB-in-docker
            MCC: '208'
            MNC: '92'
            MNC_LENGTH: 2
            TAC: 1
            UTRA_BAND_ID: 7
            DL_FREQUENCY_IN_MHZ: 2680
            UL_FREQUENCY_OFFSET_IN_MHZ: 120
            NID_CELL: 0
            NB_PRB: 50
            ENABLE_MEASUREMENT_REPORTS: 'no'
            ENABLE_X2: 'no'
            MME_S1C_IP_ADDRESS: 172.21.18.48
            ENB_S1C_IF_NAME: eth0
            ENB_S1C_IP_ADDRESS: 172.21.18.46
            ENB_S1U_IF_NAME: eth0
            ENB_S1U_IP_ADDRESS: 172.21.18.46
            ENB_X2_IP_ADDRESS: 172.21.18.46
            RRC_INACTIVITY_THRESHOLD: 0
            THREAD_PARALLEL_CONFIG: PARALLEL_SINGLE_THREAD
            USE_ADDITIONAL_OPTIONS: --RUs.[0].max_rxgain 120 --eNBs.[0].component_carriers.[0].drx_Config_present prSetup --eNBs.[0].component_carriers.[0].drx_onDurationTimer psf1 --eNBs.[0].component_carriers.[0].drx_InactivityTimer psf1 --eNBs.[0].component_carriers.[0].drx_RetransmissionTimer psf1 --eNBs.[0].component_carriers.[0].drx_longDrx_CycleStartOffset_present prSf128 --eNBs.[0].component_carriers.[0].drx_longDrx_CycleStartOffset 0 --eNBs.[0].component_carriers.[0].drx_shortDrx_Cycle sf16 --eNBs.[0].component_carriers.[0].drx_shortDrx_ShortCycleTimer 3 --log_config.global_log_options level,nocolor,time,line_num,function
        volumes:
            - /dev:/dev
        network_mode: "host"
        healthcheck:
            # pgrep does NOT work
            test: /bin/bash -c "ps aux | grep -v grep | grep -c softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
