---
{{- if .Values.multus.e1Interface.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-e1
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": {{- cat .Values.multus.e1Interface.hostInterface | nospace | quote }},
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.e1Interface.ipAdd "/" .Values.multus.e1Interface.netmask | nospace | quote }}
                        {{- if .Values.multus.e1Interface.gateway }}
                        ,"gateway": {{- cat .Values.multus.e1Interface.gateway | nospace | quote }}
                        {{- end }}
                }
        ]
        {{- if .Values.multus.e1Interface.routes }}
        ,"routes":  {{- .Values.multus.e1Interface.routes | toJson }}
        {{- end }}
      }
    }'
{{- end }}
{{- if .Values.multus.n2Interface.create }}
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-n2
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": {{- cat .Values.multus.n2Interface.hostInterface | nospace | quote }},
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.n2Interface.ipAdd "/" .Values.multus.n2Interface.netmask | nospace | quote }}
                        {{- if .Values.multus.n2Interface.gateway }}
                        ,"gateway": {{- cat .Values.multus.n2Interface.gateway | nospace | quote }}
                        {{- end }}
                }
        ]
        {{- if .Values.multus.n2Interface.routes }}
        ,"routes":  {{- .Values.multus.n2Interface.routes | toJson }}
        {{- end }}
      }
    }'
{{- end }}
{{- if .Values.multus.f1cInterface.create }}
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-f1c
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": {{- cat .Values.multus.f1cInterface.hostInterface | nospace | quote }},
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.f1cInterface.ipAdd "/" .Values.multus.f1cInterface.netmask | nospace | quote }}
                        {{- if .Values.multus.f1cInterface.gateway }}
                        ,"gateway": {{- cat .Values.multus.f1cInterface.gateway | nospace | quote }}
                        {{- end }}
                }
        ]
        {{- if .Values.multus.f1cInterface.routes }}
        ,"routes":  {{- .Values.multus.f1cInterface.routes | toJson }}
        {{- end }}
      }
    }'
{{- end }}
