---
- paths:
    source_dir: "/home/mohammed/Documents/conf_files/"
    dest_dir: docker/etc
    
- configurations:
  - filePrefix: cu
    outputfilename: "cu.fdd.conf"
    config:
    - key: Active_eNBs
      env: "@ENB_NAME@"
    - key: eNB_name
      env: "@ENB_NAME@"
    - key: plmn_list
      env:
        mcc: "@MCC@"
        mnc: "@MNC@"
        mnc_length: "@MNC_LENGTH@"
    - key: tracking_area_code
      env: "@TAC@"
    - key: local_s_if_name
      env: "@F1_IF_NAME@"
    - key: remote_s_address
      env: "@F1_DU_IP_ADDRESS@"
    - key: local_s_address
      env: "@F1_CU_IP_ADDRESS@"
    - key: eutra_band
      env: "@UTRA_BAND_ID@"
    - key: downlink_frequency
      env: "@DL_FREQUENCY_IN_MHZ@000000"
    - key: uplink_frequency_offset
      env: "@UL_FREQUENCY_OFFSET_IN_MHZ@000000"
    - key: Nid_cell
      env: "@NID_CELL@"
    - key: N_RB_DL
      env: "@NB_PRB@"
    - key: ipv4
      env: "@MME_S1C_IP_ADDRESS@"
    - key: ENB_INTERFACE_NAME_FOR_S1_MME
      env: "@S1C_IF_NAME@"
    - key: ENB_IPV4_ADDRESS_FOR_S1_MME
      env: "@F1_CU_IP_ADDRESS@"
    - key: ENB_INTERFACE_NAME_FOR_S1U
      env: "@S1U_IF_NAME@"
    - key: ENB_IPV4_ADDRESS_FOR_S1U
      env: "@F1_CU_IP_ADDRESS@"
    - key: ENB_IPV4_ADDRESS_FOR_X2C
      env: "@F1_CU_IP_ADDRESS@"
      
  - filePrefix: du
    outputfilename: "du.fdd.conf"
    config:
    - key: Active_eNBs
      env: "@ENB_NAME@"
    - key: eNB_name
      env: "@ENB_NAME@"
    - key: plmn_list
      env:
        mcc: "@MCC@"
        mnc: "@MNC@"
        mnc_length: "@MNC_LENGTH@"
    - key: tracking_area_code
      env: "@TAC@"
    - key: local_n_if_name
      env: "@F1_IF_NAME@"
    - key: remote_n_address
      env: "@F1_DU_IP_ADDRESS@"
    - key: local_n_address
      env: "@F1_CU_IP_ADDRESS@"
    - key: eutra_band
      env: "@UTRA_BAND_ID@"
    - key: downlink_frequency
      env: "@DL_FREQUENCY_IN_MHZ@000000"
    - key: uplink_frequency_offset
      env: "@UL_FREQUENCY_OFFSET_IN_MHZ@000000"
    - key: Nid_cell
      env: "@NID_CELL@"
    - key: N_RB_DL
      env: "@NB_PRB@"
      
  - filePrefix: rru.fdd
    outputfilename: "rru.fdd.conf"
    config:
    - key: local_if_name
      env: "@@"
    - key: remote_address
      env: "@@"
    - key: local_address
      env: "@@"
    - key: bands
      env: "@@"
      
  - filePrefix: rru.tdd
    outputfilename: "rru.tdd.conf"
    config:
    - key: local_if_name
      env: "@@"
    - key: remote_address
      env: "@@"
    - key: local_address
      env: "@@"
    - key: bands
      env: "@@"
      
  - filePrefix: enb.band7.tm1.25PRB.usrpb210
    outputfilename: "enb.fdd.conf"
    config:
    - key: Active_eNBs
      env: "@ENB_NAME@"
    - key: eNB_name
      env: "@ENB_NAME@"
    - key: plmn_list
      env:
        mcc: "@MCC@"
        mnc: "@MNC@"
        mnc_length: "@MNC_LENGTH@"
    - key: tracking_area_code
      env: "@TAC@"
    - key: eutra_band
      env: "@UTRA_BAND_ID@"
    - key: downlink_frequency
      env: "@DL_FREQUENCY_IN_MHZ@000000"
    - key: uplink_frequency_offset
      env: "@UL_FREQUENCY_OFFSET_IN_MHZ@000000"
    - key: Nid_cell
      env: "@NID_CELL@"
    - key: N_RB_DL
      env: "@NB_PRB@"
    - key: ipv4
      env: "@MME_S1C_IP_ADDRESS@"
    - key: ENB_INTERFACE_NAME_FOR_S1_MME
      env: "@S1C_IF_NAME@"
    - key: ENB_IPV4_ADDRESS_FOR_S1_MME
      env: "@F1_CU_IP_ADDRESS@"
    - key: ENB_INTERFACE_NAME_FOR_S1U
      env: "@S1U_IF_NAME@"
    - key: ENB_IPV4_ADDRESS_FOR_S1U
      env: "@F1_CU_IP_ADDRESS@"
    - key: ENB_IPV4_ADDRESS_FOR_X2C
      env: "@F1_CU_IP_ADDRESS@"
      
  - filePrefix: enb.band40.tm1.25PRB.FairScheduler.usrpb210
    outputfilename: "enb.tdd.conf"
    config:
    - key: Active_eNBs
      env: "@ENB_NAME@"
    - key: eNB_name
      env: "@ENB_NAME@"
    - key: plmn_list
      env:
        mcc: "@MCC@"
        mnc: "@MNC@"
        mnc_length: "@MNC_LENGTH@"
    - key: tracking_area_code
      env: "@TAC@"
    - key: eutra_band
      env: "@UTRA_BAND_ID@"
    - key: downlink_frequency
      env: "@DL_FREQUENCY_IN_MHZ@000000"
    - key: uplink_frequency_offset
      env: "@UL_FREQUENCY_OFFSET_IN_MHZ@000000"
    - key: Nid_cell
      env: "@NID_CELL@"
    - key: N_RB_DL
      env: "@NB_PRB@"
    - key: ipv4
      env: "@MME_S1C_IP_ADDRESS@"
    - key: ENB_INTERFACE_NAME_FOR_S1_MME
      env: "@S1C_IF_NAME@"
    - key: ENB_IPV4_ADDRESS_FOR_S1_MME
      env: "@F1_CU_IP_ADDRESS@"
    - key: ENB_INTERFACE_NAME_FOR_S1U
      env: "@S1U_IF_NAME@"
    - key: ENB_IPV4_ADDRESS_FOR_S1U
      env: "@F1_CU_IP_ADDRESS@"
    - key: ENB_IPV4_ADDRESS_FOR_X2C
      env: "@F1_CU_IP_ADDRESS@"
      
  - filePrefix: "rcc.band7.tm1.nfapi"
    outputfilename: "rcc.if4p5.enb.fdd.conf"
    config:
    - key: Active_eNBs
      env: "@ENB_NAME@"
    - key: eNB_name
      env: "@ENB_NAME@"
    - key: plmn_list
      env:
        mcc: "@MCC@"
        mnc: "@MNC@"
        mnc_length: "@MNC_LENGTH@"
    - key: tracking_area_code
      env: "@TAC@"
    - key: local_s_if_name
      env: "@F1_IF_NAME@"
    - key: remote_s_address
      env: "@F1_DU_IP_ADDRESS@"
    - key: local_s_address
      env: "@F1_CU_IP_ADDRESS@"
    - key: eutra_band
      env: "@UTRA_BAND_ID@"
    - key: downlink_frequency
      env: "@DL_FREQUENCY_IN_MHZ@000000"
    - key: uplink_frequency_offset
      env: "@UL_FREQUENCY_OFFSET_IN_MHZ@000000"
    - key: Nid_cell
      env: "@NID_CELL@"
    - key: N_RB_DL
      env: "@NB_PRB@"
    - key: ipv4
      env: "@MME_S1C_IP_ADDRESS@"
    - key: ENB_INTERFACE_NAME_FOR_S1_MME
      env: "@S1C_IF_NAME@"
    - key: ENB_IPV4_ADDRESS_FOR_S1_MME
      env: "@F1_CU_IP_ADDRESS@"
    - key: ENB_INTERFACE_NAME_FOR_S1U
      env: "@S1U_IF_NAME@"
    - key: ENB_IPV4_ADDRESS_FOR_S1U
      env: "@F1_CU_IP_ADDRESS@"
    - key: ENB_IPV4_ADDRESS_FOR_X2C
      env: "@F1_CU_IP_ADDRESS@"

