version: '3.8'

services:
    oai_enb0:
        image: oaisoftwarealliance/oai-enb:develop
        privileged: true
        container_name: rfsim4g-oai-enb
        networks:
            public_net:
                ipv4_address: 192.168.61.20
        environment:
            TZ: Europe/Paris
            USE_VOLUMED_CONF: 'yes'
            RFSIMULATOR: enb
            USE_ADDITIONAL_OPTIONS: --rfsim --noS1 --eNBs.[0].component_carriers.[0].mbms_dedicated_serving_cell ENABLE --log_config.global_log_options level,nocolor,time
        volumes:
            - ../../conf_files/enb.band7.tm1.25PRB.rfsim.mbms.conf:/opt/oai-enb/etc/mounted.conf
        healthcheck:
            test: /bin/bash -c "pgrep lte-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    oai_ue0:
        image: oaisoftwarealliance/oai-lte-ue:develop
        privileged: true
        container_name: rfsim4g-oai-lte-ue0
        networks:
            public_net:
                ipv4_address: 192.168.61.30
        environment:
            TZ: Europe/Paris
            HOSTNAME: oai_ue0
            RFSIMULATOR: 192.168.61.20
            MCC: '208'
            MNC: '93'
            SHORT_IMSI: '100001111'
            LTE_KEY: '8baf473f2f8fd09487cccbd7097c6862'
            OPC: 'e734f8734007d6c5ce7a0508809e7e9c'
            MSISDN: '33611123456'
            HPLMN: 20893
            USE_ADDITIONAL_OPTIONS: -C 2680000000 -r 25 --ue-rxgain 140 --ue-txgain 120 --nokrnmod 1 --rfsim --noS1 --log_config.global_log_options level,nocolor,time --noS1
        healthcheck:
            test: /bin/bash -c "pgrep lte-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    public_net:
        name: rfsim4g-oai-public-net
        ipam:
            config:
                - subnet: 192.168.61.0/26
        driver_opts:
            com.docker.network.bridge.name: "rfsim4g-public"
